### ISSUE TITLE
DEG: Habenula vs. Other brain regions

### ISSUE THREAD

**Issue by lahuuki** [LieberInstitute/Habenula_Pilot#10]
**Goal:** Identify differentially expressed genes between Habenula and other brain regions using only control donors

- [ ] Check initial iteration of the [code from Josh](https://github.com/LieberInstitute/Habenula_Bulk/blob/master/code/bulk_DE/de_analysis_gene_region_habenula.R)
- [ ] Explore Hb vs. other regions with PC analysis
- [ ] Generate consistent snpPCs for the full dataset
- [ ] design DE model with variance partition + variable exploration
- [ ] Run Lima/Voom
- [ ] GO analysis

**Comment by lcolladotor** [comment]
Did we complete this @lahuuki?

**Comment by lcolladotor** [comment]
We decided not to do this analysis.
